### ISSUE TITLE
Wrong Spotify oembed URL with performanceMode

### ISSUE THREAD

**Issue by anmartini** [ricardofiorani/oembed#8]
Hi, I've encountered a problem with the Spotify embed using performanceMode. Spotify seems to have moved its oembed endpoint from *https://**embed**.spotify.com/oembed* to *https://**open**.spotify.com/oembed*
There is a 302 redirect to the new endpoint, but the PSR-18 standard `sendRequest` doesn't allow redirects (see the note [here](https://docs.guzzlephp.org/en/stable/request-options.html#allow-redirects)), so an error occurs when the http response tries to be json decoded.
A simple fix would be to update the hard coded json in `DefaultConfig`, as the url is currently correct on oembed.com.
A more advanced solution could be to create a separate cache file that can be cleared when needed without requiring an update of the package.

**Comment by ricardofiorani** [comment]
Hey @anmartini, I'm sorry it took so long to reply.
Thank you for creating this issue.

Yeah, I've been thinking on a v2 of this lib where either the constructor receives as arguments the cached list (controlled by the implementer) or Oembed uses the PSR-18 adapter to fire a request to get the providers list and caches it itself.

In the meanwhile, I'll update the default to config containing the providers to update the Spotify Oembed endpoint.
